obstacle_range: 0.1   
raytrace_range: 3.0

robot_radius: 0.175

#the minimum distance that must be maintained between robot and obstscale
inflation_radius: 0.1     

max_obstacle_height: 0.6
min_obstacle_height: 0.0
observation_sources: scan
scan: {data_type: LaserScan, topic: my_robot/laser/scan, marking: true, clearing: true, expected_update_rate: 0}
