local_costmap:
   global_frame: odom
   robot_base_frame: base_link
   update_frequency: 10.0
   publish_frequency: 8.0
   static_map: true
   rolling_window: false
   width: 0.5
   height: 0.5
   resolution: 0.01
   transform_tolerance: 2.0
